export const locales = ['ru', 'ua', 'en'];

export const copy = {
  ru: {
    code: 'ru', htmlLang: 'ru', label: 'RU',
    nav: ['Главная','О нас','Как это работает','Преимущества','FAQ','Контакты'],
    apply: 'Оставить заявку', start: 'Начать сейчас', learn: 'Узнать больше',
    eyebrow: 'БОЛЬШЕ ЧЕМ РАБОТА', hero1: 'ТВОЯ ВСЕЛЕННАЯ', hero2: 'ВОЗМОЖНОСТЕЙ',
    heroCopy: 'Cosmo Agency — это команда, которая помогает зарабатывать на стриминговых платформах, развиваться и чувствовать поддержку на каждом этапе.',
    platforms: 'Мы работаем с ведущими платформами:', others: 'и другими',
    benefits: [
      ['rocket','Стабильный\nдоход','Прозрачная система выплат, никаких скрытых условий.'],
      ['star','Полное обучение','Мы научим всему с нуля — от технической настройки до уверенного онлайн-общения.'],
      ['heart','Поддержка 24/7','Ты никогда не остаёшься одна — наша команда всегда рядом.'],
      ['crown','Безопасность\nи конфиденциальность','Твои данные под защитой. Мы ценим твоё доверие.'],
      ['bars','Реальные\nперспективы','Развивайся, увеличивай доход и достигай своих целей вместе с нами.'],
    ],
    howEyebrow: 'КАК ВСЁ РАБОТАЕТ?', howTitle1: 'ПРОСТЫЕ ШАГИ', howTitle2: 'К БОЛЬШИМ ЦЕЛЯМ',
    steps: [
      ['01','doc','Оставляешь\nзаявку','Заполняй короткую форму на сайте'],
      ['02','user','Проходишь\nобучение','Получаешь все необходимые знания и поддержку'],
      ['03','play','Выходишь\nв эфир','Начинаешь работать на топовых платформах'],
      ['04','bars','Зарабатываешь\nи развиваешься','Мы всегда рядом, чтобы помочь тебе расти'],
    ],
    footerWords: ['СТРИМИ','РАЗВИВАЙСЯ','ЗАРАБАТЫВАЙ'], footerTag: 'ТВОЙ ПОТЕНЦИАЛ — НАША ВСЕЛЕННАЯ', join: 'Стать частью Cosmo',
    aboutEyebrow: 'О COSMO AGENCY', aboutTitle: 'Команда и поддержка на каждом этапе',
    aboutCopy: 'COSMO Agency помогает начать работу на стриминговых платформах: от обучения и технической настройки до ежедневной поддержки. Мы работаем с ведущими платформами и уделяем отдельное внимание конфиденциальности, прозрачным условиям и понятному процессу для каждой участницы команды.',
    faqTitle: 'Частые вопросы',
    faq: [
      ['С какого возраста можно оставить заявку?','Заявку можно оставить с 18 лет.'],
      ['Нужен ли опыт?','Нет. В COSMO предусмотрено обучение с нуля и поддержка на каждом этапе.'],
      ['Как проходит обучение?','Команда помогает с технической настройкой, базовыми процессами и подготовкой к работе на стриминговых платформах.'],
      ['Как обеспечивается конфиденциальность?','Мы внимательно относимся к персональным данным и используем их только для обработки заявки и дальнейшей коммуникации.'],
      ['Какие платформы используются?','Среди платформ — Stripchat, MyFreeCams, Chaturbate и другие.'],
      ['Как связаться с COSMO?','Оставь заявку через форму на сайте или напиши на hello@cosmo.agency.'],
    ],
    privacy: 'Политика конфиденциальности', terms: 'Условия использования', contacts: 'Контакты',
    form: { close:'Закрыть', title:'Оставить заявку', intro:'Оставь контакты — команда COSMO свяжется с тобой и расскажет о следующих шагах.', thanks:'Спасибо!', success:'Заявка отправлена. Мы свяжемся с тобой по указанному номеру или Telegram.', name:'Имя', namePh:'Как тебя зовут?', phone:'Номер телефона', telegram:'Telegram', consent:'Я подтверждаю, что мне исполнилось 18 лет, и соглашаюсь с политикой конфиденциальности.', sending:'Отправляем…', submit:'Отправить заявку ↗', required:'* обязательные поля', error:'Не удалось отправить заявку. Попробуй ещё раз или напиши на hello@cosmo.agency.' },
  },
  ua: {
    code: 'ua', htmlLang: 'uk', label: 'UA',
    nav: ['Головна','Про нас','Як це працює','Переваги','FAQ','Контакти'],
    apply: 'Залишити заявку', start: 'Почати зараз', learn: 'Дізнатися більше',
    eyebrow: 'БІЛЬШЕ НІЖ РОБОТА', hero1: 'ТВІЙ ВСЕСВІТ', hero2: 'МОЖЛИВОСТЕЙ',
    heroCopy: 'Cosmo Agency — це команда, яка допомагає заробляти на стримінгових платформах, розвиватися та відчувати підтримку на кожному етапі.',
    platforms: 'Ми працюємо з провідними платформами:', others: 'та іншими',
    benefits: [
      ['rocket','Стабільний\nдохід','Прозора система виплат, жодних прихованих умов.'],
      ['star','Повне навчання','Ми навчимо всьому з нуля — від технічного налаштування до впевненого онлайн-спілкування.'],
      ['heart','Підтримка 24/7','Ти ніколи не залишаєшся одна — наша команда завжди поруч.'],
      ['crown','Безпека\nта конфіденційність','Твої дані під захистом. Ми цінуємо твою довіру.'],
      ['bars','Реальні\nперспективи','Розвивайся, збільшуй дохід і досягай своїх цілей разом із нами.'],
    ],
    howEyebrow: 'ЯК УСЕ ПРАЦЮЄ?', howTitle1: 'ПРОСТІ КРОКИ', howTitle2: 'ДО ВЕЛИКИХ ЦІЛЕЙ',
    steps: [
      ['01','doc','Залишаєш\nзаявку','Заповни коротку форму на сайті'],
      ['02','user','Проходиш\nнавчання','Отримуєш усі необхідні знання та підтримку'],
      ['03','play','Виходиш\nв ефір','Починаєш працювати на топових платформах'],
      ['04','bars','Заробляєш\nі розвиваєшся','Ми завжди поруч, щоб допомогти тобі зростати'],
    ],
    footerWords: ['СТРИМ','РОЗВИВАЙСЯ','ЗАРОБЛЯЙ'], footerTag: 'ТВІЙ ПОТЕНЦІАЛ — НАШ ВСЕСВІТ', join: 'Стати частиною Cosmo',
    aboutEyebrow: 'ПРО COSMO AGENCY', aboutTitle: 'Команда та підтримка на кожному етапі',
    aboutCopy: 'COSMO Agency допомагає почати роботу на стримінгових платформах: від навчання та технічного налаштування до щоденної підтримки. Ми працюємо з провідними платформами та приділяємо окрему увагу конфіденційності, прозорим умовам і зрозумілому процесу для кожної учасниці команди.',
    faqTitle: 'Часті запитання',
    faq: [
      ['З якого віку можна залишити заявку?','Заявку можна залишити з 18 років.'],
      ['Чи потрібен досвід?','Ні. У COSMO передбачене навчання з нуля та підтримка на кожному етапі.'],
      ['Як проходить навчання?','Команда допомагає з технічним налаштуванням, базовими процесами та підготовкою до роботи на стримінгових платформах.'],
      ['Як забезпечується конфіденційність?','Ми уважно ставимося до персональних даних і використовуємо їх лише для обробки заявки та подальшої комунікації.'],
      ['Які платформи використовуються?','Серед платформ — Stripchat, MyFreeCams, Chaturbate та інші.'],
      ['Як зв’язатися з COSMO?','Залиш заявку через форму на сайті або напиши на hello@cosmo.agency.'],
    ],
    privacy: 'Політика конфіденційності', terms: 'Умови використання', contacts: 'Контакти',
    form: { close:'Закрити', title:'Залишити заявку', intro:'Залиш контакти — команда COSMO зв’яжеться з тобою та розповість про наступні кроки.', thanks:'Дякуємо!', success:'Заявку надіслано. Ми зв’яжемося з тобою за вказаним номером або в Telegram.', name:'Ім’я', namePh:'Як тебе звати?', phone:'Номер телефону', telegram:'Telegram', consent:'Я підтверджую, що мені виповнилося 18 років, і погоджуюся з політикою конфіденційності.', sending:'Надсилаємо…', submit:'Надіслати заявку ↗', required:'* обов’язкові поля', error:'Не вдалося надіслати заявку. Спробуй ще раз або напиши на hello@cosmo.agency.' },
  },
  en: {
    code: 'en', htmlLang: 'en', label: 'EN',
    nav: ['Home','About','How it works','Benefits','FAQ','Contacts'],
    apply: 'Apply now', start: 'Start now', learn: 'Learn more',
    eyebrow: 'MORE THAN A JOB', hero1: 'YOUR UNIVERSE', hero2: 'OF OPPORTUNITIES',
    heroCopy: 'Cosmo Agency is a team that helps you earn on streaming platforms, grow, and feel supported at every stage.',
    platforms: 'We work with leading platforms:', others: 'and others',
    benefits: [
      ['rocket','Stable\nincome','Transparent payout system with no hidden conditions.'],
      ['star','Full training','We teach you from scratch — from technical setup to confident online communication.'],
      ['heart','24/7 support','You are never left alone — our team is always by your side.'],
      ['crown','Safety &\nprivacy','Your data is protected. We value your trust.'],
      ['bars','Real\nopportunities','Grow, increase your income and reach your goals together with us.'],
    ],
    howEyebrow: 'HOW DOES IT WORK?', howTitle1: 'SIMPLE STEPS', howTitle2: 'TO BIG GOALS',
    steps: [
      ['01','doc','Submit an\napplication','Fill out a short form on the website'],
      ['02','user','Complete\ntraining','Get all the knowledge and support you need'],
      ['03','play','Go\nlive','Start working on leading platforms'],
      ['04','bars','Earn\nand grow','We are always here to help you grow'],
    ],
    footerWords: ['STREAM','GROW','EARN'], footerTag: 'YOUR POTENTIAL — OUR UNIVERSE', join: 'Join Cosmo',
    aboutEyebrow: 'ABOUT COSMO AGENCY', aboutTitle: 'A team that supports you at every stage',
    aboutCopy: 'COSMO Agency helps you start working on streaming platforms: from training and technical setup to daily support. We work with leading platforms and pay special attention to privacy, transparent conditions and a clear process for every member of the team.',
    faqTitle: 'Frequently asked questions',
    faq: [
      ['What age can I apply from?','Applications are accepted from age 18.'],
      ['Do I need experience?','No. COSMO provides training from scratch and support at every stage.'],
      ['How does training work?','The team helps with technical setup, core processes and preparation for work on streaming platforms.'],
      ['How is privacy protected?','We handle personal data carefully and use it only to process your application and continue communication.'],
      ['Which platforms do you work with?','Platforms include Stripchat, MyFreeCams, Chaturbate and others.'],
      ['How can I contact COSMO?','Submit an application through the website form or email hello@cosmo.agency.'],
    ],
    privacy: 'Privacy Policy', terms: 'Terms of Use', contacts: 'Contacts',
    form: { close:'Close', title:'Apply now', intro:'Leave your contact details — the COSMO team will get in touch and explain the next steps.', thanks:'Thank you!', success:'Your application has been sent. We will contact you by phone or Telegram.', name:'Name', namePh:'What is your name?', phone:'Phone number', telegram:'Telegram', consent:'I confirm that I am 18 or older and agree to the Privacy Policy.', sending:'Sending…', submit:'Submit application ↗', required:'* required fields', error:'We could not send your application. Please try again or email hello@cosmo.agency.' },
  },
};

export function getCopy(locale = 'ru') { return copy[locale] || copy.ru; }
