'use client';

import { useMemo, useState } from 'react';

const copy = {
  ru: { back:'Назад на сайт', title:'Регистрация в COSMO', intro:'Создай рабочий профиль и пройди обязательную верификацию личности и возраста.', steps:['Данные','О себе','Аккаунт','Верификация','Готово'], next:'Продолжить', prev:'Назад', submit:'Отправить на проверку', sending:'Отправляем…', name:'Имя и фамилия', dob:'Дата рождения', phone:'Номер телефона', telegram:'Telegram', country:'Страна', city:'Город', experience:'Опыт', schedule:'Желаемый график', languages:'Языки', email:'Email', password:'Пароль', docType:'Документ', front:'Фото документа — лицевая сторона', backDoc:'Фото документа — обратная сторона', consent:'Я подтверждаю, что мне исполнилось 18 лет, данные указаны верно и я согласна на обработку данных для регистрации и проверки.', expPh:'Коротко расскажи, был ли опыт на стриминговых платформах', schedulePh:'Например: 5 дней в неделю, вечер', langPh:'Например: русский, украинский, английский', passHint:'Минимум 8 символов. Этот пароль будет использоваться для входа в личный кабинет.', docHint:'Документы хранятся приватно. В Telegram отправляются только данные заявки и ссылка для менеджера — сами файлы документов туда не отправляются.', reviewTitle:'Аккаунт отправлен на проверку', reviewCopy:'Менеджер COSMO проверит данные и подтвердит аккаунт. Статус можно отслеживать в личном кабинете.', account:'Открыть личный кабинет', error:'Не удалось завершить регистрацию. Проверь данные и попробуй ещё раз.', errs:{name:'Укажи корректные имя и фамилию.',dob:'Укажи корректную дату рождения. Регистрация доступна только с 18 лет.',phone:'Укажи корректный номер телефона в международном формате.',telegram:'Telegram должен быть в формате @username.',country:'Укажи страну.',city:'Укажи город.',email:'Укажи корректный email.',password:'Пароль должен содержать минимум 8 символов.',front:'Загрузи лицевую сторону документа.',back:'Загрузи обратную сторону документа.',file:'JPG, PNG, WEBP или PDF до 8 MB.',consent:'Подтверди согласие на обработку данных.'}},
  ua: { back:'Назад на сайт', title:'Реєстрація в COSMO', intro:'Створи робочий профіль і пройди обов’язкову верифікацію особи та віку.', steps:['Дані','Про себе','Акаунт','Верифікація','Готово'], next:'Продовжити', prev:'Назад', submit:'Надіслати на перевірку', sending:'Надсилаємо…', name:'Ім’я та прізвище', dob:'Дата народження', phone:'Номер телефону', telegram:'Telegram', country:'Країна', city:'Місто', experience:'Досвід', schedule:'Бажаний графік', languages:'Мови', email:'Email', password:'Пароль', docType:'Документ', front:'Фото документа — лицьова сторона', backDoc:'Фото документа — зворотна сторона', consent:'Я підтверджую, що мені виповнилося 18 років, дані вказані правильно та я погоджуюся на обробку даних для реєстрації й перевірки.', expPh:'Коротко розкажи, чи був досвід на стримінгових платформах', schedulePh:'Наприклад: 5 днів на тиждень, вечір', langPh:'Наприклад: українська, російська, англійська', passHint:'Мінімум 8 символів. Цей пароль використовуватиметься для входу в особистий кабінет.', docHint:'Документи зберігаються приватно. У Telegram надсилаються лише дані заявки та посилання для менеджера — самі файли документів туди не надсилаються.', reviewTitle:'Акаунт надіслано на перевірку', reviewCopy:'Менеджер COSMO перевірить дані та підтвердить акаунт. Статус можна відстежувати в особистому кабінеті.', account:'Відкрити особистий кабінет', error:'Не вдалося завершити реєстрацію. Перевір дані та спробуй ще раз.', errs:{name:'Вкажи коректні ім’я та прізвище.',dob:'Вкажи коректну дату народження. Реєстрація доступна лише з 18 років.',phone:'Вкажи коректний номер телефону у міжнародному форматі.',telegram:'Telegram має бути у форматі @username.',country:'Вкажи країну.',city:'Вкажи місто.',email:'Вкажи коректний email.',password:'Пароль має містити щонайменше 8 символів.',front:'Завантаж лицьову сторону документа.',back:'Завантаж зворотну сторону документа.',file:'JPG, PNG, WEBP або PDF до 8 MB.',consent:'Підтвердь згоду на обробку даних.'}},
  en: { back:'Back to site', title:'Register with COSMO', intro:'Create your work profile and complete the required identity and age verification.', steps:['Details','About you','Account','Verification','Done'], next:'Continue', prev:'Back', submit:'Submit for review', sending:'Submitting…', name:'Full name', dob:'Date of birth', phone:'Phone number', telegram:'Telegram', country:'Country', city:'City', experience:'Experience', schedule:'Preferred schedule', languages:'Languages', email:'Email', password:'Password', docType:'Document', front:'Document photo — front side', backDoc:'Document photo — back side', consent:'I confirm that I am 18 or older, the information is correct, and I consent to the processing of my data for registration and verification.', expPh:'Briefly describe any previous streaming-platform experience', schedulePh:'For example: 5 days a week, evenings', langPh:'For example: English, Ukrainian, Russian', passHint:'Minimum 8 characters. You will use this password to sign in to your account.', docHint:'Documents are stored privately. Telegram receives only application details and a manager link — the document files themselves are never sent there.', reviewTitle:'Your account is under review', reviewCopy:'A COSMO manager will review your information and approve the account. You can track the status in your personal account.', account:'Open my account', error:'Registration could not be completed. Check your details and try again.', errs:{name:'Enter your real first and last name.',dob:'Enter a valid date of birth. Registration is 18+ only.',phone:'Enter a valid international phone number.',telegram:'Telegram must look like @username.',country:'Enter your country.',city:'Enter your city.',email:'Enter a valid email address.',password:'Password must be at least 8 characters.',front:'Upload the front of your document.',back:'Upload the back of your document.',file:'JPG, PNG, WEBP or PDF up to 8 MB.',consent:'Confirm consent to data processing.'}}
};

const NAME_RE = /^[\p{L}][\p{L}'’ -]{1,78}$/u;
const EMAIL_RE = /^[^\s@]+@[^\s@]+\.[^\s@]{2,}$/;
const TG_RE = /^@[A-Za-z0-9_]{5,32}$/;
const FILE_TYPES = new Set(['image/jpeg','image/png','image/webp','application/pdf']);
const MAX_FILE = 8 * 1024 * 1024;

function validPhone(value){ const digits=String(value||'').replace(/\D/g,''); return /^\+?[\d\s().-]+$/.test(value) && digits.length>=8 && digits.length<=15 && !/^(\d)\1{7,}$/.test(digits); }
function validDob(value){ const d=new Date(value); if(!value||Number.isNaN(d.getTime())) return false; const y=d.getUTCFullYear(); if(y<1950) return false; const now=new Date(); let age=now.getUTCFullYear()-y; const md=now.getUTCMonth()-d.getUTCMonth(); if(md<0||(md===0&&now.getUTCDate()<d.getUTCDate())) age--; return age>=18 && d<=now; }
function validateFile(file){ return file && file.size>0 && file.size<=MAX_FILE && FILE_TYPES.has(file.type); }
const Input = ({ label, error, ...props }) => <label className={`reg-field ${error?'is-error':''}`}><span>{label}</span><input {...props}/>{error&&<small className="reg-field__error">{error}</small>}</label>;

export default function RegistrationWizard({ locale='ru' }){
  const t=copy[locale]||copy.ru; const [step,setStep]=useState(0); const [status,setStatus]=useState('idle'); const [error,setError]=useState(''); const [errors,setErrors]=useState({});
  const [form,setForm]=useState({full_name:'',date_of_birth:'',phone:'',telegram:'',country:'',city:'',experience:'',schedule:'',languages:'',email:'',password:'',document_type:'passport',consent:false});
  const [files,setFiles]=useState({document_front:null,document_back:null}); const progress=useMemo(()=>((step+1)/t.steps.length)*100,[step,t.steps.length]);
  const setValue=(key)=>(e)=>{ const value=e.target.type==='checkbox'?e.target.checked:e.target.value; setForm(p=>({...p,[key]:value})); setErrors(p=>({...p,[key]:''})); };
  const checkStep=(s=step)=>{ const e={}; if(s===0){ if(!NAME_RE.test(form.full_name.trim())||form.full_name.trim().split(/\s+/).length<2)e.full_name=t.errs.name; if(!validDob(form.date_of_birth))e.date_of_birth=t.errs.dob; if(!validPhone(form.phone))e.phone=t.errs.phone; if(form.telegram && !TG_RE.test(form.telegram.trim()))e.telegram=t.errs.telegram; }
    if(s===1){ if(form.country.trim().length<2)e.country=t.errs.country; if(form.city.trim().length<2)e.city=t.errs.city; }
    if(s===2){ if(!EMAIL_RE.test(form.email.trim()))e.email=t.errs.email; if(form.password.length<8)e.password=t.errs.password; }
    if(s===3){ if(!validateFile(files.document_front))e.document_front=files.document_front?t.errs.file:t.errs.front; if(!validateFile(files.document_back))e.document_back=files.document_back?t.errs.file:t.errs.back; if(!form.consent)e.consent=t.errs.consent; }
    setErrors(e); return Object.keys(e).length===0; };
  const next=()=>{ if(checkStep()) setStep(s=>s+1); };
  const pickFile=(key)=>(e)=>{ const file=e.target.files?.[0]||null; setFiles(p=>({...p,[key]:file})); setErrors(p=>({...p,[key]:file&&validateFile(file)?'':(file?t.errs.file:'')})); };
  async function submit(){ if(!checkStep(3)) return; setStatus('sending'); setError(''); const fd=new FormData(); Object.entries(form).forEach(([k,v])=>fd.append(k,String(v))); fd.append('locale',locale); fd.append('document_front',files.document_front); fd.append('document_back',files.document_back); try{ const res=await fetch('/api/register',{method:'POST',body:fd}); const body=await res.json().catch(()=>({})); if(!res.ok) throw new Error(body.error||'registration_failed'); setStatus('success'); setStep(4);}catch(e){console.error(e);setStatus('error');setError(t.error);} }
  return <main className="register-page"><div className="register-stars" aria-hidden="true"/><section className="register-shell"><aside className="register-aside"><a href={`/${locale}/`} className="register-logo"><img src="/img/main-logo (1).webp" alt="COSMO Agency"/></a><div><p className="eyebrow">COSMO ONBOARDING</p><h1>{t.title}</h1><p>{t.intro}</p></div><div className="register-security"><span>18+</span><p>PRIVATE KYC<br/>SECURE REVIEW</p></div></aside>
  <section className="register-card"><div className="register-progress"><span style={{width:`${progress}%`}}/></div><div className="register-stepper">{t.steps.map((label,i)=><div className={i<=step?'active':''} key={label}><b>{String(i+1).padStart(2,'0')}</b><span>{label}</span></div>)}</div><div className="register-stage">
  {step===0&&<><p className="register-kicker">01 / PERSONAL DETAILS</p><h2>{t.steps[0]}</h2><div className="reg-grid"><Input label={t.name} error={errors.full_name} value={form.full_name} onChange={setValue('full_name')}/><Input label={t.dob} error={errors.date_of_birth} type="date" value={form.date_of_birth} onChange={setValue('date_of_birth')} max={new Date().toISOString().slice(0,10)}/><Input label={t.phone} error={errors.phone} type="tel" value={form.phone} onChange={setValue('phone')} placeholder="+380 ..."/><Input label={t.telegram} error={errors.telegram} value={form.telegram} onChange={setValue('telegram')} placeholder="@username"/></div></>}
  {step===1&&<><p className="register-kicker">02 / PROFILE</p><h2>{t.steps[1]}</h2><div className="reg-grid"><Input label={t.country} error={errors.country} value={form.country} onChange={setValue('country')}/><Input label={t.city} error={errors.city} value={form.city} onChange={setValue('city')}/></div><label className="reg-field"><span>{t.experience}</span><textarea value={form.experience} onChange={setValue('experience')} placeholder={t.expPh} maxLength="1000"/></label><div className="reg-grid"><Input label={t.schedule} value={form.schedule} onChange={setValue('schedule')} placeholder={t.schedulePh} maxLength="160"/><Input label={t.languages} value={form.languages} onChange={setValue('languages')} placeholder={t.langPh} maxLength="160"/></div></>}
  {step===2&&<><p className="register-kicker">03 / ACCOUNT</p><h2>{t.steps[2]}</h2><div className="reg-grid reg-grid--single"><Input label={t.email} error={errors.email} type="email" value={form.email} onChange={setValue('email')} autoComplete="email"/><Input label={t.password} error={errors.password} type="password" value={form.password} onChange={setValue('password')} autoComplete="new-password"/></div><p className="reg-note">{t.passHint}</p></>}
  {step===3&&<><p className="register-kicker">04 / IDENTITY VERIFICATION</p><h2>{t.steps[3]}</h2><label className="reg-field"><span>{t.docType}</span><select value={form.document_type} onChange={setValue('document_type')}><option value="passport">Passport / ID</option><option value="id_card">ID Card</option></select></label><div className="document-grid"><label className={`document-drop ${files.document_front?'has-file':''} ${errors.document_front?'is-error':''}`}><input type="file" accept="image/jpeg,image/png,image/webp,application/pdf" onChange={pickFile('document_front')}/><span>01</span><strong>{t.front}</strong><small>{files.document_front?.name||'JPG / PNG / WEBP / PDF · max 8 MB'}</small>{errors.document_front&&<em>{errors.document_front}</em>}</label><label className={`document-drop ${files.document_back?'has-file':''} ${errors.document_back?'is-error':''}`}><input type="file" accept="image/jpeg,image/png,image/webp,application/pdf" onChange={pickFile('document_back')}/><span>02</span><strong>{t.backDoc}</strong><small>{files.document_back?.name||'JPG / PNG / WEBP / PDF · max 8 MB'}</small>{errors.document_back&&<em>{errors.document_back}</em>}</label></div><p className="reg-privacy">✦ {t.docHint}</p><label className={`reg-consent ${errors.consent?'is-error':''}`}><input type="checkbox" checked={form.consent} onChange={setValue('consent')}/><span>{t.consent}</span></label>{errors.consent&&<small className="reg-field__error">{errors.consent}</small>}</>}
  {step===4&&<div className="register-success"><div className="register-orbit">✓</div><p className="register-kicker">05 / REVIEW</p><h2>{t.reviewTitle}</h2><p>{t.reviewCopy}</p><a className="pink-btn" href={`/${locale}/account/`}>{t.account} ↗</a></div>}{error&&<p className="register-error">{error}</p>}</div>
  {step<4&&<div className="register-nav"><button type="button" className="register-back" onClick={()=>step===0?(window.location.href=`/${locale}/`):setStep(s=>s-1)}>{step===0?t.back:t.prev}</button>{step<3?<button type="button" className="pink-btn" onClick={next}>{t.next} ↗</button>:<button type="button" className="pink-btn" disabled={status==='sending'} onClick={submit}>{status==='sending'?t.sending:t.submit} ↗</button>}</div>}</section></section></main>;
}
